// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agpeebvrrcytghmilzss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFncGVlYnZycmN5dGdobWlsenNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMDc2MTAsImV4cCI6MjA3NjU4MzYxMH0.BlS6PZjuVsDuBW_mc5Y_4pjdLuFc5-kANYJBSm1iwFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});